# Usa una imagen de OpenJDK para ejecutar la aplicación
FROM openjdk:17-jdk-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo JAR desde la ruta correcta en el contexto de la construcción
COPY src/api/target/webReservas-0.0.1-SNAPSHOT.jar app.jar

# Expone el puerto de la aplicación
EXPOSE 8080

# Ejecuta el archivo JAR
CMD ["java", "-jar", "app.jar"]
