version: '3.8'

services:
  db:
    image: postgres:14
    container_name: proyecto-fin-de-grado-db
    environment:
      POSTGRES_DB: asadorDatabase
      POSTGRES_USER: roberto
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: proyecto-fin-de-grado-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/asadordatabase
      SPRING_DATASOURCE_USERNAME: roberto
      SPRING_DATASOURCE_PASSWORD: 12345

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: proyecto-fin-de-grado-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
