# Paso 1: Usar una imagen de OpenJDK para ejecutar la aplicación
FROM openjdk:17-jdk-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo JAR desde la ruta correcta en el contexto de la construcción
COPY src/api/target/webReservas-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto de la aplicación
EXPOSE 8080

# Ejecutar el archivo JAR
CMD ["java", "-jar", "app.jar"]
